### ISSUE TITLE
🐛 [BUG] - Can't rate cardio exercises

### ISSUE THREAD

**Issue by TheSecondWing** [madmustachecompany/Blast-Workout-App#75]
### Description

Hello,
It seems we cannot rate (6 to 10) the cardio exercises.
Is this normal ?
Thanks!

### Reproduction steps

```bash
1. Go to '...'
2. Tap on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### OS

None

**Comment by madmustachecompany** [comment]
Yes, this is intentional.
We've deliberately "deactivated" it on cardio exercises because we're wondering whether we can find a more relevant way of measuring intensity on this type of exercise. While waiting to find a solution that suits us and to avoid possible future conflicts (if we were to modify the rating system), we've decided not to enable the RPE rating system on cardio exercises for the time being.

**Comment by TheSecondWing** [comment]
Totally understandable. Thanks for the great info. Closing ticket. Have a nice day.
